version: "3.8"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    restart: unless-stopped
    networks:
      - belight-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env.local
    restart: unless-stopped
    networks:
      - belight-network
    depends_on:
      - api

networks:
  belight-network:
    driver: bridge
