"use client";

interface ExportProps {
  data: any;
  filename: string;
}

export function exportToMarkdown({ data, filename }: ExportProps) {
  const timestamp = new Date().toLocaleString();
  const title = filename || "BeLight-Report";

  let md = `# ${title}\n\n`;
  md += `**Generated:** ${timestamp}  \n`;
  md += `**Source:** BeLight Nexus AI — belight-nexus.ai\n\n`;
  md += `---\n\n`;

  const renderValue = (val: any, depth: number = 0): string => {
    const indent = "  ".repeat(depth);
    if (val === null || val === undefined) return "";
    if (typeof val === "string" || typeof val === "number" || typeof val === "boolean") {
      return String(val) + "\n";
    }
    if (Array.isArray(val)) {
      return val.map((item, i) => `${indent}- ${renderValue(item, depth + 1)}`).join("");
    }
    if (typeof val === "object") {
      return Object.entries(val)
        .map(([key, value]) => {
          if (value === null || value === undefined) return "";
          return `${indent}### ${key}\n\n${renderValue(value, depth + 1)}\n`;
        })
        .join("");
    }
    return "";
  };

  md += renderValue(data);
  md += `\n---\n\n*This report was generated by BeLight Nexus AI. For more information, visit our platform.*\n`;

  const blob = new Blob([md], { type: "text/markdown" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportToJSON({ data, filename }: ExportProps) {
  const title = filename || "BeLight-Report";
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${title.replace(/\s+/g, "-").toLowerCase()}-${Date.now()}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function ExportButtons({ data, filename }: ExportProps) {
  if (!data) return null;
  return (
    <div className="flex gap-2 mb-4">
      <button
        onClick={() => exportToMarkdown({ data, filename })}
        className="bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs px-3 py-2 rounded-lg transition-colors"
      >
        📥 Export Markdown
      </button>
      <button
        onClick={() => exportToJSON({ data, filename })}
        className="bg-gray-800 hover:bg-gray-700 text-gray-300 text-xs px-3 py-2 rounded-lg transition-colors"
      >
        📥 Export JSON
      </button>
    </div>
  );
}
